version: '3.7'

services:
  prometheus:
    build:
      context: docker/prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
